# Site settings
baseURL = "https://gandalfdg.github.io/"
languageCode = "en-US"
title = "Ms. Kiersten"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "RSS", "sitemap"]
disableHugoGeneratorInject = true

# Local preview mode
relativeURLs = true
uglyURLs = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2024 Jack Case"

[params]

  # Metadata for search engines and social sharing
  author = "Kiersten Case"
  description = "Hi! I'm Ms. Kiersten"
  shareImage = "images/social.jpg"
  twitterHandle = "onepagelove"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/kiersten-cropped.jpg"
      position = "center top"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "My Work"

      [[params.links.list1.link]]
        text = "Youtube"
        url = "https://www.youtube.com/@Ms.KierstensMusicCorner"
        new_tab = true # new tab

      [[params.links.list1.link]]
        text = "Instagram"
        url = "https://www.instagram.com/ms.kierstensmusicroom/"
        new_tab = true # Default, open at same tab

      [[params.links.list1.link]]
        text = "TikTok"
        url = "https://www.tiktok.com/@ms..kiersten"
        new_tab = true

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Contact Me"

      [[params.links.list2.link]]
        text = "Email"
        url = "mailto:mskierstenmusic@gmail.com"


  # Links List #3
  # [[params.links]]
  #   [params.links.list3]
  #     heading = "Network"

  #     [[params.links.list3.link]]
  #       text = "Link One"
  #       url = "#"

  #     [[params.links.list3.link]]
  #       text = "Link Two"
  #       url = "#"

  #     [[params.links.list3.link]]
  #       text = "Link Three"
  #       url = "#"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
